Docs: deploy-code file updated
BeccaLyria/discord-documentation pull request #563
Opened 2021-10-04 07:27 UTC by princeprag

# Pull Request

## Description:

 
The deploy-code file is updated. It now clearly states how to invite the local instance of Becca to the server with appropriate permissions and scopes.

## Related Issue:

Closes #559

2021-10-04 13:41 UTC, nhcarrigan requested changes
This is off to a great start! Some grammar/verbiage tweaks, and I've got an image we can use for the permissions.

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +##Generating the link from dashboard in developer portal
```suggestion
## Generating the link from dashboard in developer portal
```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +The next step is to invite your instance of Becca to your server. You can use the Discord Developer portal to generate an invitation link.
```suggestion
The next step is to invite your instance of Becca to your server. You can use the Discord Developer portal to generate an invite link.
```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +Go to [Application](https://discord.com/developers/applications) in the Discord Developer Portal.
```suggestion
Go to the [Applications](https://discord.com/developers/applications) page in the Discord Developer Portal.
```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +- Open the new application that you have created in previous step.
```suggestion
- Open the new application that you created earlier.
```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +- In the scopes section click checkboxes with `applications.commands` (you can't run slash commands without it) and `bot`.
```suggestion
- In the scopes section, select the checkboxes with `applications.commands` (allows your bot to register slash commands) and `bot`.
```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +
```suggestion

Your choices should look like this:

![image of choices list](https://cdn.nhcarrigan.com/content/discord/becca-permissions.png)

```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +
Uploaded an image to our CDN for this. 🙂

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +You can then copy the invitation link from the scopes section above using the `Copy` button.
```suggestion
You can then copy the invite link from the scopes section above using the `Copy` button.

```

2021-10-04 13:41 UTC, nhcarrigan commented on docs/deploy-code.md
> +
````suggestion
It looks something like: 

```txt
https://discord.com/oauth2/authorize?client_id=CLIENT_ID_HERE&permissions=INTEGER_CODE_HERE&scope=applications.commands%20bot
```
````

Block quote format doesn't work here. Also, let's use a multi-line code block so we get horizontal scroll on the link.

2021-10-05 02:40 UTC, princeprag commented
@nhcarrigan Changes done!

2021-10-05 02:41 UTC, nhcarrigan approved these changes
Looks good to me!

2021-10-05 02:51 UTC, merged